### ISSUE TITLE
Bug: 感觉 projects 页面有点卡

### ISSUE THREAD

**Issue by MurphyZX** [lin-stephanie/astro-antfustyle-theme#1]
### Bug description

https://astro-antfustyle-theme.vercel.app/projects/
不知道为什么一进去页面会很卡顿

### Steps to reproduce

无

### Validations

- [X] Check that there isn't [already an issue](https://github.com/lin-stephanie/astro-antfustyle-theme/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lin-stephanie/astro-antfustyle-theme/discussions) or refer to the [posts on the live demo](https://astro-antfustyle-theme.vercel.app/blog/).

**Comment by lin-stephanie** [comment]
@MurphyZX  因为这个页面用到的背景动画在每帧需要进行复杂计算和全屏重绘，会消耗 CPU，如果在设备性能不足以支持的情况下可能就会出现你说的问题（antfu/antfu.me#86 中也有人提到）。

当前在 https://github.com/lin-stephanie/astro-antfustyle-theme/commit/8fb85e1bae2a95c021f21a795e9d94bf84f3fee3 中做了一定调整，你可以再看下。因为我自己设备（`macOS 14.3, arm64 Apple M3, Chrome`）上是没有感觉到这个问题的，如果你愿意可以提供下你的环境信息（调用 `npx envinfo --system --binaries --browsers`）让我了解下；以及如果还是有问题，你可以移除这个背景。

**Comment by MurphyZX** [comment]
thx，我的环境是 windows11，目前已经不卡了。

**Comment by lin-stephanie** [comment]
好嘞，多谢提问！
